# Generated by Django 6.0.1 on 2026-01-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='medicines_b_expiry__f30147_idx',
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='medicines_b_batch_n_b9d4e3_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='medicines_p_invoice_48bae4_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='medicines_p_purchas_c72bd0_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='medicine',
        ),
        migrations.RemoveIndex(
            model_name='stockadjustment',
            name='medicines_s_adjustm_ed249c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockadjustment',
            name='medicines_s_adjustm_7f0c3c_idx',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='adjusted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
    ]
