# Generated by Django 6.0.1 on 2026-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_batch_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='doctor',
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='doctor_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
