# Generated by Django 6.0.1 on 2026-01-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='medicine_name',
            field=models.CharField(default='Unknown Medicine', help_text='Captured name at time of sale', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.medicine'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.medicine'),
        ),
    ]
